"""Integration tests for the LLM-wired /configurations/generate endpoint.

Covers:
- LLM path when AI_ENABLED=True and GEMINI_API_KEY is set
- Fallback to rule-based when LLM raises
- Rule-based path when AI_ENABLED=False
- Retry logic: LLM retried up to 3 times before fallback
- generation_method tag in response payload
"""
from __future__ import annotations

import uuid
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from finspark.api.v1.endpoints.configurations import (
    _MAX_LLM_RETRIES,
    _llm_generate_with_retry,
    _rule_based_generate,
    generate_configuration,
)
from finspark.schemas.configurations import ConfigGenerateRequest, ConfigStatus
from finspark.services.llm.client import GeminiAPIError

pytestmark = pytest.mark.unit


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _make_generate_request(**kwargs: Any) -> ConfigGenerateRequest:
    defaults = {
        "tenant_id": uuid.uuid4(),
        "adapter_id": uuid.uuid4(),
        "document_ids": [],
        "overrides": {},
        "llm_hint": "test hint",
    }
    defaults.update(kwargs)
    return ConfigGenerateRequest(**defaults)


_SAMPLE_LLM_PAYLOAD: dict[str, Any] = {
    "base_url": "https://api.example.com",
    "endpoints": [{"path": "/score", "method": "POST", "description": "Credit score"}],
    "auth": {"type": "api_key", "config": {"key_name": "X-API-Key", "in": "header"}},
    "timeout_ms": 3000,
    "retry_count": 3,
    "retry_backoff": "exponential",
    "field_mappings": [
        {"source_field": "customer.pan", "target_field": "pan_number", "transform": None, "required": True}
    ],
    "headers": {"Content-Type": "application/json"},
    "notes": "Generated by Gemini",
}


# ---------------------------------------------------------------------------
# _rule_based_generate
# ---------------------------------------------------------------------------


class TestRuleBasedGenerate:
    def test_returns_scaffold_with_required_keys(self) -> None:
        body = _make_generate_request()
        result = _rule_based_generate(body)
        assert "base_url" in result
        assert "endpoints" in result
        assert "auth" in result
        assert "timeout_ms" in result
        assert "retry_count" in result
        assert "field_mappings" in result

    def test_notes_mention_adapter_id(self) -> None:
        body = _make_generate_request()
        result = _rule_based_generate(body)
        assert str(body.adapter_id) in result["notes"]


# ---------------------------------------------------------------------------
# _llm_generate_with_retry
# ---------------------------------------------------------------------------


class TestLlmGenerateWithRetry:
    async def test_returns_on_first_success(self) -> None:
        body = _make_generate_request()
        with (
            patch("finspark.api.v1.endpoints.configurations.GeminiClient"),
            patch(
                "finspark.api.v1.endpoints.configurations.generate_config",
                new_callable=AsyncMock,
                return_value=_SAMPLE_LLM_PAYLOAD,
            ),
        ):
            result = await _llm_generate_with_retry(body)

        assert result == _SAMPLE_LLM_PAYLOAD

    async def test_retries_on_error_then_succeeds(self) -> None:
        body = _make_generate_request()
        call_count = 0

        async def _flaky(*args: Any, **kwargs: Any) -> dict[str, Any]:
            nonlocal call_count
            call_count += 1
            if call_count < 2:
                raise GeminiAPIError("transient error")
            return _SAMPLE_LLM_PAYLOAD

        with (
            patch("finspark.api.v1.endpoints.configurations.GeminiClient"),
            patch("finspark.api.v1.endpoints.configurations.generate_config", side_effect=_flaky),
            patch("finspark.api.v1.endpoints.configurations.asyncio.sleep", new_callable=AsyncMock),
        ):
            result = await _llm_generate_with_retry(body)

        assert result == _SAMPLE_LLM_PAYLOAD
        assert call_count == 2

    async def test_raises_after_max_retries(self) -> None:
        body = _make_generate_request()

        async def _always_fail(*args: Any, **kwargs: Any) -> None:
            raise GeminiAPIError("persistent error")

        with (
            patch("finspark.api.v1.endpoints.configurations.GeminiClient"),
            patch("finspark.api.v1.endpoints.configurations.generate_config", side_effect=_always_fail),
            patch("finspark.api.v1.endpoints.configurations.asyncio.sleep", new_callable=AsyncMock),
        ):
            with pytest.raises(GeminiAPIError, match="persistent error"):
                await _llm_generate_with_retry(body)

    async def test_retry_count_matches_max(self) -> None:
        """Exactly _MAX_LLM_RETRIES calls before giving up."""
        body = _make_generate_request()
        call_count = 0

        async def _always_fail(*args: Any, **kwargs: Any) -> None:
            nonlocal call_count
            call_count += 1
            raise GeminiAPIError("fail")

        with (
            patch("finspark.api.v1.endpoints.configurations.GeminiClient"),
            patch("finspark.api.v1.endpoints.configurations.generate_config", side_effect=_always_fail),
            patch("finspark.api.v1.endpoints.configurations.asyncio.sleep", new_callable=AsyncMock),
        ):
            with pytest.raises(GeminiAPIError):
                await _llm_generate_with_retry(body)

        assert call_count == _MAX_LLM_RETRIES


# ---------------------------------------------------------------------------
# generate_configuration endpoint — full path tests
# ---------------------------------------------------------------------------


class TestGenerateConfigurationEndpoint:
    def _fake_db(self) -> AsyncMock:
        return AsyncMock()

    def _fake_user(self) -> MagicMock:
        return MagicMock()

    async def test_llm_path_when_ai_enabled(self) -> None:
        body = _make_generate_request()

        with (
            patch(
                "finspark.api.v1.endpoints.configurations.settings"
            ) as mock_settings,
            patch(
                "finspark.api.v1.endpoints.configurations._llm_generate_with_retry",
                new_callable=AsyncMock,
                return_value=_SAMPLE_LLM_PAYLOAD,
            ),
        ):
            mock_settings.AI_ENABLED = True
            mock_settings.GEMINI_API_KEY = "test-key"
            result = await generate_configuration(body, self._fake_db(), self._fake_user())

        assert result.status == ConfigStatus.DRAFT
        assert result.payload["_generation_method"] == "llm"
        assert result.payload["base_url"] == _SAMPLE_LLM_PAYLOAD["base_url"]

    async def test_rule_based_path_when_ai_disabled(self) -> None:
        body = _make_generate_request()

        with patch(
            "finspark.api.v1.endpoints.configurations.settings"
        ) as mock_settings:
            mock_settings.AI_ENABLED = False
            mock_settings.GEMINI_API_KEY = "test-key"
            result = await generate_configuration(body, self._fake_db(), self._fake_user())

        assert result.status == ConfigStatus.DRAFT
        assert result.payload["_generation_method"] == "rule_based"

    async def test_rule_based_path_when_no_api_key(self) -> None:
        body = _make_generate_request()

        with patch(
            "finspark.api.v1.endpoints.configurations.settings"
        ) as mock_settings:
            mock_settings.AI_ENABLED = True
            mock_settings.GEMINI_API_KEY = ""
            result = await generate_configuration(body, self._fake_db(), self._fake_user())

        assert result.payload["_generation_method"] == "rule_based"

    async def test_fallback_to_rule_based_when_llm_fails(self) -> None:
        body = _make_generate_request()

        with (
            patch(
                "finspark.api.v1.endpoints.configurations.settings"
            ) as mock_settings,
            patch(
                "finspark.api.v1.endpoints.configurations._llm_generate_with_retry",
                new_callable=AsyncMock,
                side_effect=GeminiAPIError("API quota exceeded"),
            ),
        ):
            mock_settings.AI_ENABLED = True
            mock_settings.GEMINI_API_KEY = "test-key"
            result = await generate_configuration(body, self._fake_db(), self._fake_user())

        assert result.status == ConfigStatus.DRAFT
        assert result.payload["_generation_method"] == "rule_based"

    async def test_response_has_required_config_record_fields(self) -> None:
        body = _make_generate_request()

        with patch(
            "finspark.api.v1.endpoints.configurations.settings"
        ) as mock_settings:
            mock_settings.AI_ENABLED = False
            mock_settings.GEMINI_API_KEY = ""
            result = await generate_configuration(body, self._fake_db(), self._fake_user())

        assert result.id is not None
        assert result.tenant_id == body.tenant_id
        assert result.adapter_id == body.adapter_id
        assert result.version == 1
        assert result.created_at is not None
        assert result.updated_at is not None
