"""add contract_test_runs table

Revision ID: 6b02bf242aec
Revises: f8af5a676619
Create Date: 2026-05-10 03:22:12.501171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b02bf242aec'
down_revision: Union[str, Sequence[str], None] = 'f8af5a676619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_test_runs',
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('adapter_name', sa.String(length=255), nullable=False),
    sa.Column('adapter_version', sa.String(length=50), nullable=False),
    sa.Column('total_endpoints', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_test_runs_configuration_id'), 'contract_test_runs', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_contract_test_runs_tenant_id'), 'contract_test_runs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_test_runs_tenant_id'), table_name='contract_test_runs')
    op.drop_index(op.f('ix_contract_test_runs_configuration_id'), table_name='contract_test_runs')
    op.drop_table('contract_test_runs')
    # ### end Alembic commands ###
