"""add api_call_logs table

Revision ID: f8af5a676619
Revises: f98c690eeb83
Create Date: 2026-05-10 03:05:12.858681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8af5a676619'
down_revision: Union[str, Sequence[str], None] = 'f98c690eeb83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_logs',
    sa.Column('configuration_id', sa.String(length=36), nullable=False),
    sa.Column('adapter_name', sa.String(length=255), nullable=False),
    sa.Column('adapter_version', sa.String(length=50), nullable=False),
    sa.Column('endpoint_path', sa.String(length=500), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('schema_match', sa.Boolean(), nullable=False),
    sa.Column('drift_fields', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_logs_adapter_name'), 'api_call_logs', ['adapter_name'], unique=False)
    op.create_index(op.f('ix_api_call_logs_adapter_version'), 'api_call_logs', ['adapter_version'], unique=False)
    op.create_index(op.f('ix_api_call_logs_configuration_id'), 'api_call_logs', ['configuration_id'], unique=False)
    op.create_index(op.f('ix_api_call_logs_tenant_id'), 'api_call_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_call_logs_tenant_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_configuration_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_adapter_version'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_adapter_name'), table_name='api_call_logs')
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
