"""
FinSpark Integration Orchestration Engine — Pydantic v2 schema registry.

Import convention:
    from app.schemas import TenantRead, AdapterCreate, ...
    from app.schemas.adapter import AuthScheme, AdapterVersionRead
"""
from .common import (
    ErrorDetail,
    ErrorResponse,
    OrchestratorBase,
    Page,
    PageMeta,
    ResourceId,
    SemVer,
    SlugStr,
    SoftDeleteMixin,
    SuccessResponse,
    TenantId,
    TimestampedMixin,
)
from .document import (
    ApiSpecFormat,
    ApiSpecParseResult,
    BrdParseResult,
    DocumentListItem,
    DocumentRead,
    DocumentStatus,
    DocumentType,
    DocumentUploadRequest,
    DocumentUploadResponse,
    ExtractedAuthRequirement,
    ExtractedEndpoint,
    ExtractedFieldMapping,
    ExtractedIntegrationHint,
    ParseResult,
    SowParseResult,
)
from .adapter import (
    AdapterCategory,
    AdapterCreate,
    AdapterEndpoint,
    AdapterListItem,
    AdapterRead,
    AdapterStatus,
    AdapterUpdate,
    AdapterVersionCreate,
    AdapterVersionRead,
    ApiKeyAuth,
    AuthScheme,
    AuthSchemeType,
    BearerAuth,
    BasicAuth,
    EndpointRole,
    HmacAuth,
    MtlsAuth,
    NoAuth,
    OAuth2AuthorizationCode,
    OAuth2ClientCredentials,
    RateLimitConfig,
)
from .configuration import (
    CircuitBreakerPolicy,
    ConfigurationCreate,
    ConfigurationListItem,
    ConfigurationRead,
    ConfigurationStatus,
    ConfigurationUpdate,
    FieldMapping,
    HookDefinition,
    HookEvent,
    HookRuntime,
    RetryPolicy,
    Transformation,
    TransformationType,
)
from .tenant import (
    CredentialRef,
    DataResidencyRegion,
    IpAllowlistEntry,
    TenantAdapterCredentials,
    TenantContact,
    TenantCreate,
    TenantFeatureFlags,
    TenantListItem,
    TenantQuota,
    TenantRead,
    TenantStatus,
    TenantTier,
    TenantUpdate,
)
from .audit_log import (
    AuditAction,
    AuditActor,
    AuditLogCreate,
    AuditLogListItem,
    AuditLogQueryParams,
    AuditLogRead,
    AuditOutcome,
    AuditResourceType,
    AuditSeverity,
    FieldDiff,
    ResourceDiff,
)
from .test_result import (
    AssertionResult,
    MockEndpointConfig,
    MockResponseFixture,
    TestAssertion,
    TestCase,
    TestCaseResult,
    TestRunCreate,
    TestRunListItem,
    TestRunMode,
    TestRunRead,
    TestRunStatus,
    VersionComparisonResult,
    VersionComparisonRunCreate,
    VersionTestTarget,
)
from .webhook import (
    DeliveryStatus,
    WebhookCreate,
    WebhookDeliveryAttempt,
    WebhookDeliveryRead,
    WebhookEventType,
    WebhookListItem,
    WebhookPayload,
    WebhookRead,
    WebhookRetryConfig,
    WebhookStatus,
    WebhookUpdate,
)
from .version_comparison import (
    AdapterVersionDiff,
    AdapterVersionDiffRequest,
    ChangeType,
    CompatibilityLevel,
    ConfigVersionDiff,
    ConfigVersionDiffRequest,
    EndpointChange,
    FieldChange,
    PromotionDecision,
    PromotionRecord,
    PromotionRequest,
    RollbackRequest,
)
from .api import (
    AdapterCreateRequest,
    AdapterCreateResponse,
    AdapterVersionDiffResponse,
    AutoConfigRequest,
    AutoConfigResponse,
    AutoConfigSuggestion,
    ConfigurationCreateRequest,
    ConfigurationCreateResponse,
    DocumentUploadInitRequest,
    DocumentUploadInitResponse,
    HealthCheck,
    PromotionRequestBody,
    PromotionResponse,
    RollbackRequestBody,
    RollbackResponse,
    TenantCreateRequest,
    TenantCreateResponse,
    TestRunCreateRequest,
    TestRunCreateResponse,
    VersionComparisonCreateRequest,
    VersionComparisonReadResponse,
    WebhookCreateRequest,
    WebhookCreateResponse,
)

__all__ = [
    # common
    "ErrorDetail", "ErrorResponse", "OrchestratorBase", "Page", "PageMeta",
    "ResourceId", "SemVer", "SlugStr", "SoftDeleteMixin", "SuccessResponse",
    "TenantId", "TimestampedMixin",
    # document
    "ApiSpecFormat", "ApiSpecParseResult", "BrdParseResult", "DocumentListItem",
    "DocumentRead", "DocumentStatus", "DocumentType", "DocumentUploadRequest",
    "DocumentUploadResponse", "ExtractedAuthRequirement", "ExtractedEndpoint",
    "ExtractedFieldMapping", "ExtractedIntegrationHint", "ParseResult", "SowParseResult",
    # adapter
    "AdapterCategory", "AdapterCreate", "AdapterEndpoint", "AdapterListItem",
    "AdapterRead", "AdapterStatus", "AdapterUpdate", "AdapterVersionCreate",
    "AdapterVersionRead", "ApiKeyAuth", "AuthScheme", "AuthSchemeType",
    "BearerAuth", "BasicAuth", "EndpointRole", "HmacAuth", "MtlsAuth",
    "NoAuth", "OAuth2AuthorizationCode", "OAuth2ClientCredentials", "RateLimitConfig",
    # configuration
    "CircuitBreakerPolicy", "ConfigurationCreate", "ConfigurationListItem",
    "ConfigurationRead", "ConfigurationStatus", "ConfigurationUpdate",
    "FieldMapping", "HookDefinition", "HookEvent", "HookRuntime",
    "RetryPolicy", "Transformation", "TransformationType",
    # tenant
    "CredentialRef", "DataResidencyRegion", "IpAllowlistEntry",
    "TenantAdapterCredentials", "TenantContact", "TenantCreate",
    "TenantFeatureFlags", "TenantListItem", "TenantQuota", "TenantRead",
    "TenantStatus", "TenantTier", "TenantUpdate",
    # audit
    "AuditAction", "AuditActor", "AuditLogCreate", "AuditLogListItem",
    "AuditLogQueryParams", "AuditLogRead", "AuditOutcome", "AuditResourceType",
    "AuditSeverity", "FieldDiff", "ResourceDiff",
    # test
    "AssertionResult", "MockEndpointConfig", "MockResponseFixture", "TestAssertion",
    "TestCase", "TestCaseResult", "TestRunCreate", "TestRunListItem", "TestRunMode",
    "TestRunRead", "TestRunStatus", "VersionComparisonResult",
    "VersionComparisonRunCreate", "VersionTestTarget",
    # webhook
    "DeliveryStatus", "WebhookCreate", "WebhookDeliveryAttempt",
    "WebhookDeliveryRead", "WebhookEventType", "WebhookListItem", "WebhookPayload",
    "WebhookRead", "WebhookRetryConfig", "WebhookStatus", "WebhookUpdate",
    # version comparison
    "AdapterVersionDiff", "AdapterVersionDiffRequest", "ChangeType",
    "CompatibilityLevel", "ConfigVersionDiff", "ConfigVersionDiffRequest",
    "EndpointChange", "FieldChange", "PromotionDecision", "PromotionRecord",
    "PromotionRequest", "RollbackRequest",
    # api
    "AdapterCreateRequest", "AdapterCreateResponse", "AdapterVersionDiffResponse",
    "AutoConfigRequest", "AutoConfigResponse", "AutoConfigSuggestion",
    "ConfigurationCreateRequest", "ConfigurationCreateResponse",
    "DocumentUploadInitRequest", "DocumentUploadInitResponse", "HealthCheck",
    "PromotionRequestBody", "PromotionResponse", "RollbackRequestBody",
    "RollbackResponse", "TenantCreateRequest", "TenantCreateResponse",
    "TestRunCreateRequest", "TestRunCreateResponse",
    "VersionComparisonCreateRequest", "VersionComparisonReadResponse",
    "WebhookCreateRequest", "WebhookCreateResponse",
]
