"""Tests for the LLM + rule-based config generation pipeline (Issue #30).

Covers:
- Rule-based path when AI is disabled
- LLM path with rule augmentation when AI is enabled
- Fallback to rule-based when LLM raises
- _augment_with_rule_based correctly merges confidence scores
- _augment_with_rule_based backfills unmapped source fields
"""
from __future__ import annotations

from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

from fastapi import BackgroundTasks

import pytest

from finspark.api.routes.configurations import _augment_with_rule_based
from finspark.services.config_engine.field_mapper import ConfigGenerator
from finspark.services.llm.client import GeminiAPIError


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def generator() -> ConfigGenerator:
    return ConfigGenerator()


def _make_av_dict(
    *,
    adapter_name: str = "test-adapter",
    version: str = "v1",
    base_url: str = "https://api.example.com",
) -> dict[str, Any]:
    return {
        "adapter_name": adapter_name,
        "version": version,
        "base_url": base_url,
        "auth_type": "api_key",
        "endpoints": [{"path": "/score", "method": "POST", "description": "Credit score"}],
        "request_schema": {
            "properties": {
                "pan_number": {"type": "string"},
                "mobile_number": {"type": "string"},
            },
            "required": ["pan_number"],
        },
        "response_schema": {
            "properties": {
                "credit_score": {"type": "integer"},
            }
        },
    }


def _make_parsed_result() -> dict[str, Any]:
    return {
        "fields": [
            {"name": "pan_number", "data_type": "string", "source_section": "request"},
            {"name": "mobile", "data_type": "string", "source_section": "request"},
        ],
        "summary": "Credit check API BRD",
    }


_SAMPLE_LLM_CONFIG: dict[str, Any] = {
    "base_url": "https://api.example.com",
    "endpoints": [{"path": "/score", "method": "POST", "description": "Credit score"}],
    "auth": {"type": "api_key", "config": {}},
    "timeout_ms": 3000,
    "retry_count": 3,
    "retry_backoff": "exponential",
    "field_mappings": [
        {
            "source_field": "pan_number",
            "target_field": "pan",
            "transformation": None,
            "confidence": 0.5,  # LLM self-assessed — will be overridden by rule-based
            "is_confirmed": False,
        }
    ],
    "headers": {},
    "notes": "Generated by Gemini",
}


# ---------------------------------------------------------------------------
# _augment_with_rule_based unit tests
# ---------------------------------------------------------------------------


class TestAugmentWithRuleBased:
    def test_confidence_overridden_by_rule_based(self, generator: ConfigGenerator) -> None:
        """Rule-based confidence replaces LLM's self-assessed confidence."""
        parsed = _make_parsed_result()
        av_dict = _make_av_dict()

        # LLM gives confidence 0.5 for pan_number -> pan
        llm_config: dict[str, Any] = {
            "field_mappings": [
                {
                    "source_field": "pan_number",
                    "target_field": "pan",
                    "confidence": 0.5,
                    "is_confirmed": False,
                    "transformation": None,
                }
            ]
        }

        result = _augment_with_rule_based(llm_config, parsed, av_dict, generator)
        mappings = result["field_mappings"]
        pan_mapping = next(
            (m for m in mappings if m.get("source_field") == "pan_number"), None
        )
        assert pan_mapping is not None
        # Rule-based synonym match for pan_number -> pan_number gives 1.0
        assert pan_mapping["confidence"] == 1.0

    def test_backfills_unmapped_source_fields(self, generator: ConfigGenerator) -> None:
        """Fields present in rule-based but absent from LLM are appended."""
        parsed = _make_parsed_result()
        av_dict = _make_av_dict()

        # LLM only mapped pan_number; rule-based will also map mobile_number
        llm_config: dict[str, Any] = {
            "field_mappings": [
                {
                    "source_field": "pan_number",
                    "target_field": "pan_number",
                    "confidence": 0.8,
                    "is_confirmed": True,
                    "transformation": None,
                }
            ]
        }

        result = _augment_with_rule_based(llm_config, parsed, av_dict, generator)
        source_fields = [m.get("source_field") for m in result["field_mappings"]]
        assert "pan_number" in source_fields
        # mobile is in parsed_result fields — rule-based may find it
        # (at minimum, pan_number must be preserved)
        assert len(result["field_mappings"]) >= 1

    def test_preserves_llm_base_url_and_endpoints(self, generator: ConfigGenerator) -> None:
        """Non-field_mappings keys from LLM config are preserved unchanged."""
        parsed = _make_parsed_result()
        av_dict = _make_av_dict()

        result = _augment_with_rule_based(_SAMPLE_LLM_CONFIG.copy(), parsed, av_dict, generator)

        assert result["base_url"] == _SAMPLE_LLM_CONFIG["base_url"]
        assert result["timeout_ms"] == _SAMPLE_LLM_CONFIG["timeout_ms"]
        assert result["retry_count"] == _SAMPLE_LLM_CONFIG["retry_count"]
        assert result["notes"] == _SAMPLE_LLM_CONFIG["notes"]

    def test_empty_llm_mappings_filled_by_rule_based(self, generator: ConfigGenerator) -> None:
        """When LLM returns no field_mappings, rule-based fills them."""
        parsed = _make_parsed_result()
        av_dict = _make_av_dict()

        llm_config: dict[str, Any] = {
            "base_url": "https://api.example.com",
            "field_mappings": [],
        }

        result = _augment_with_rule_based(llm_config, parsed, av_dict, generator)
        # Rule-based should have produced at least one mapping for pan_number
        assert len(result["field_mappings"]) >= 1

    def test_generation_path_key_not_added_by_augment(self, generator: ConfigGenerator) -> None:
        """_augment_with_rule_based does not add _generation_path; caller does."""
        parsed = _make_parsed_result()
        av_dict = _make_av_dict()
        result = _augment_with_rule_based({}, parsed, av_dict, generator)
        assert "_generation_path" not in result


# ---------------------------------------------------------------------------
# generate_configuration endpoint — pipeline path tests
# ---------------------------------------------------------------------------


class TestGenerateConfigurationPipeline:
    """Tests for the full pipeline via mocked settings + DB."""

    def _make_mock_doc(self, parsed_result: dict[str, Any] | None = None) -> MagicMock:
        doc = MagicMock()
        doc.parsed_result = __import__("json").dumps(parsed_result or _make_parsed_result())
        doc.filename = "test.pdf"
        return doc

    def _make_mock_av(self) -> MagicMock:
        av = MagicMock()
        av.adapter_id = "test-adapter"
        av.version = "v1"
        av.base_url = "https://api.example.com"
        av.auth_type = "api_key"
        av.endpoints = None
        av.request_schema = None
        av.response_schema = None
        return av

    def _make_mock_db(self, doc: MagicMock, av: MagicMock) -> AsyncMock:
        """DB session that returns the given doc and adapter version on execute.

        Also patches Configuration.__init__ so that flush() fills in id/timestamps
        on any Configuration object added to the session.
        """
        import uuid
        from datetime import UTC, datetime

        db = AsyncMock()

        def _make_result(scalar_value: Any) -> MagicMock:
            result = MagicMock()
            result.scalar_one_or_none.return_value = scalar_value
            return result

        db.execute = AsyncMock(
            side_effect=[_make_result(doc), _make_result(av)]
        )

        def _add_and_fill(obj: Any) -> None:
            """Set id + timestamps on Configuration instances so pydantic validation passes."""
            from finspark.models.configuration import Configuration
            if isinstance(obj, Configuration):
                if not obj.id:
                    obj.id = str(uuid.uuid4())
                if not obj.created_at:
                    obj.created_at = datetime.now(UTC)
                if not obj.updated_at:
                    obj.updated_at = datetime.now(UTC)

        db.add = MagicMock(side_effect=_add_and_fill)
        db.flush = AsyncMock()
        return db

    def _make_mock_tenant(self) -> MagicMock:
        t = MagicMock()
        t.tenant_id = "tenant-1"
        t.tenant_name = "Test Tenant"
        return t

    def _make_mock_audit(self) -> AsyncMock:
        audit = AsyncMock()
        audit.log = AsyncMock()
        return audit

    @pytest.mark.asyncio
    async def test_rule_based_path_when_ai_disabled(self) -> None:
        """When AI is disabled, rule-based generator is used directly."""
        from finspark.api.routes.configurations import generate_configuration
        from finspark.schemas.configurations import GenerateConfigRequest

        request = GenerateConfigRequest(
            document_id="doc-1",
            adapter_version_id="av-1",
            name="Test Config",
        )

        with patch("finspark.api.routes.configurations.settings") as mock_settings:
            mock_settings.ai_enabled = False
            mock_settings.gemini_api_key = ""

            result = await generate_configuration(
                request=request,
                background_tasks=BackgroundTasks(),
                db=self._make_mock_db(self._make_mock_doc(), self._make_mock_av()),
                tenant=self._make_mock_tenant(),
                generator=ConfigGenerator(),
                audit=self._make_mock_audit(),
            )

        assert result.data.status == "configured"
        assert result.data.version == 1
        payload = result.message
        assert "rule_based" in payload

    @pytest.mark.asyncio
    async def test_llm_path_with_augmentation(self) -> None:
        """When AI is enabled and Gemini key present, LLM runs then rule augments."""
        from finspark.api.routes.configurations import generate_configuration
        from finspark.schemas.configurations import GenerateConfigRequest

        request = GenerateConfigRequest(
            document_id="doc-1",
            adapter_version_id="av-1",
            name="Test Config",
        )

        with (
            patch("finspark.api.routes.configurations.settings") as mock_settings,
            patch(
                "finspark.api.routes.configurations.GeminiClient",
                return_value=MagicMock(),
            ),
            patch(
                "finspark.api.routes.configurations.generate_config_llm",
                new_callable=AsyncMock,
                return_value=_SAMPLE_LLM_CONFIG.copy(),
            ),
        ):
            mock_settings.ai_enabled = True
            mock_settings.gemini_api_key = "test-key"

            result = await generate_configuration(
                request=request,
                background_tasks=BackgroundTasks(),
                db=self._make_mock_db(self._make_mock_doc(), self._make_mock_av()),
                tenant=self._make_mock_tenant(),
                generator=ConfigGenerator(),
                audit=self._make_mock_audit(),
            )

        assert "llm_with_rule_augment" in result.message
        assert result.data.status == "configured"

    @pytest.mark.asyncio
    async def test_fallback_to_rule_based_when_llm_raises(self) -> None:
        """When LLM raises GeminiAPIError, fallback to rule-based generation."""
        from finspark.api.routes.configurations import generate_configuration
        from finspark.schemas.configurations import GenerateConfigRequest

        request = GenerateConfigRequest(
            document_id="doc-1",
            adapter_version_id="av-1",
            name="Test Config",
        )

        with (
            patch("finspark.api.routes.configurations.settings") as mock_settings,
            patch(
                "finspark.api.routes.configurations.GeminiClient",
                return_value=MagicMock(),
            ),
            patch(
                "finspark.api.routes.configurations.generate_config_llm",
                new_callable=AsyncMock,
                side_effect=GeminiAPIError("quota exceeded"),
            ),
        ):
            mock_settings.ai_enabled = True
            mock_settings.gemini_api_key = "test-key"

            result = await generate_configuration(
                request=request,
                background_tasks=BackgroundTasks(),
                db=self._make_mock_db(self._make_mock_doc(), self._make_mock_av()),
                tenant=self._make_mock_tenant(),
                generator=ConfigGenerator(),
                audit=self._make_mock_audit(),
            )

        assert "rule_based_fallback" in result.message
        assert result.data.status == "configured"

    @pytest.mark.asyncio
    async def test_fallback_on_generic_exception(self) -> None:
        """Any exception from LLM triggers fallback to rule-based."""
        from finspark.api.routes.configurations import generate_configuration
        from finspark.schemas.configurations import GenerateConfigRequest

        request = GenerateConfigRequest(
            document_id="doc-1",
            adapter_version_id="av-1",
            name="Test Config",
        )

        with (
            patch("finspark.api.routes.configurations.settings") as mock_settings,
            patch(
                "finspark.api.routes.configurations.GeminiClient",
                return_value=MagicMock(),
            ),
            patch(
                "finspark.api.routes.configurations.generate_config_llm",
                new_callable=AsyncMock,
                side_effect=ConnectionError("network error"),
            ),
        ):
            mock_settings.ai_enabled = True
            mock_settings.gemini_api_key = "test-key"

            result = await generate_configuration(
                request=request,
                background_tasks=BackgroundTasks(),
                db=self._make_mock_db(self._make_mock_doc(), self._make_mock_av()),
                tenant=self._make_mock_tenant(),
                generator=ConfigGenerator(),
                audit=self._make_mock_audit(),
            )

        assert "rule_based_fallback" in result.message

    @pytest.mark.asyncio
    async def test_rule_based_path_when_no_api_key(self) -> None:
        """When ai_enabled=True but gemini_api_key empty, uses rule-based."""
        from finspark.api.routes.configurations import generate_configuration
        from finspark.schemas.configurations import GenerateConfigRequest

        request = GenerateConfigRequest(
            document_id="doc-1",
            adapter_version_id="av-1",
            name="Test Config",
        )

        with patch("finspark.api.routes.configurations.settings") as mock_settings:
            mock_settings.ai_enabled = True
            mock_settings.gemini_api_key = ""

            result = await generate_configuration(
                request=request,
                background_tasks=BackgroundTasks(),
                db=self._make_mock_db(self._make_mock_doc(), self._make_mock_av()),
                tenant=self._make_mock_tenant(),
                generator=ConfigGenerator(),
                audit=self._make_mock_audit(),
            )

        assert "rule_based" in result.message

    @pytest.mark.asyncio
    async def test_generation_path_recorded_in_config(self) -> None:
        """_generation_path key is persisted into full_config."""
        from finspark.api.routes.configurations import generate_configuration
        from finspark.schemas.configurations import GenerateConfigRequest

        request = GenerateConfigRequest(
            document_id="doc-1",
            adapter_version_id="av-1",
            name="Test Config",
        )

        import json

        db = self._make_mock_db(self._make_mock_doc(), self._make_mock_av())
        added_config: dict[str, Any] = {}

        original_add = db.add

        def capture_add(obj: Any) -> None:
            nonlocal added_config
            if hasattr(obj, "full_config") and obj.full_config:
                added_config = json.loads(obj.full_config)
            original_add(obj)

        db.add = capture_add

        with patch("finspark.api.routes.configurations.settings") as mock_settings:
            mock_settings.ai_enabled = False
            mock_settings.gemini_api_key = ""

            await generate_configuration(
                request=request,
                background_tasks=BackgroundTasks(),
                db=db,
                tenant=self._make_mock_tenant(),
                generator=ConfigGenerator(),
                audit=self._make_mock_audit(),
            )

        assert "_generation_path" in added_config
        assert added_config["_generation_path"] == "rule_based"

    @pytest.mark.asyncio
    async def test_audit_log_includes_generation_path(self) -> None:
        """audit.log is called with generation_path in details."""
        from finspark.api.routes.configurations import generate_configuration
        from finspark.schemas.configurations import GenerateConfigRequest

        request = GenerateConfigRequest(
            document_id="doc-1",
            adapter_version_id="av-1",
            name="Test Config",
        )

        audit = self._make_mock_audit()

        with patch("finspark.api.routes.configurations.settings") as mock_settings:
            mock_settings.ai_enabled = False
            mock_settings.gemini_api_key = ""

            await generate_configuration(
                request=request,
                background_tasks=BackgroundTasks(),
                db=self._make_mock_db(self._make_mock_doc(), self._make_mock_av()),
                tenant=self._make_mock_tenant(),
                generator=ConfigGenerator(),
                audit=audit,
            )

        audit.log.assert_awaited_once()
        _, kwargs = audit.log.call_args
        assert "generation_path" in kwargs.get("details", {})
